!level
  repoVcsSetups:
    local: 
      !repoVcs
        workingPath: "local"
        referenceStoreName: "test-local-ref"
        checkpointStoreName: "test-local-checkpoints"
  steps:
    - !elaborate
      descriptionId: "level-data/demo/description:elaborate:intro"
    
    - !instruct # instruct the user to take action
      descriptionId: "level-data/demo/description:instruct:simple-example"
    
    - !verifyInput
      answer: "2"
    
    - !illustrate
      descriptionId: "level-data/demo/description:illustrate:explain-blocking"
    
    - !verifyInput
      descriptionId: "level-data/demo/description:verify-input:puzzle"
      answer: "${{ demo/answer:puzzle }}"
    
    - !loadOneReference
      repoSetupName: local
      referenceName: clean

    - !elaborate
      descriptionId: "level-data/demo/description:elaborate:explain-load-reference"
    
    - !openWorkingPath
      repoSetupName: local

    - !instruct
      descriptionId: "level-data/demo/description:instruct:count-local-branch"
    - !verifyInput
      answer: "6"
    
    - !instruct
      descriptionId: "level-data/demo/description:instruct:merge"
    - !verifyOneRepo
      repoSetupName: local
      referenceName: merge

    - !checkpoint
      checkpointName: kerker

    - !elaborate
      descriptionId: "level-data/demo/description:elaborate:checkpoint"
    
    - !instruct
      descriptionId: "level-data/demo/description:instruct:unmerge"
    - !verifyOneRepo
      repoSetupName: local
      referenceName: clean

    - !checkpoint
      checkpointName: noking

    - !instruct # illustrate that IllustrateStep puts out illustrations
      descriptionId: "level-data/demo/description:illustrate:load-checkpoint"

    - !elaborate
      descriptionId: "level-data/demo/description:elaborate:end"

